//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;



    public partial class LocationDBEntities : DbContext
    {
        public LocationDBEntities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAreas> AdminAreas { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<MainCities> MainCities { get; set; }
    }
}
